const text = `
One might suspect that Hesiod was the first to look for such a thing-or some one else who put love or desire among existing things as a principle, as Parmenides, too, does; for he, in constructing the genesis of the universe, says:

"Love first of all the Gods she planned".

And Hesiod says:

"First of all things was chaos made, and then Broad-breasted earth... And love, 'mid all the gods pre-eminent".

Which implies that among existing things there must be from the first a cause which will move things and bring them together. How these thinkers should be arranged with regard to priority of discovery let us be allowed to decide later; but since the contraries of the various forms of good were also perceived to be present in nature-not only order and the beautiful, but also disorder and the ugly, and bad things in greater number than good, and ignoble things than beautiful-therefore another thinker introduced friendship and strife, each of the two the cause of one of these two sets of qualities. For if we were to follow out the view of Empedocles, and interpret it according to its meaning and not to its lisping expression, we should find that friendship is the cause of good things, and strife of bad. Therefore, if we said that Empedocles in a sense both mentions, and is the first to mention, the bad and the good as principles, we should perhaps be right, since the cause of all goods is the good itself.

These thinkers, as we say, evidently grasped, and to this extent, two of the causes which we distinguished in our work on nature-the matter and the source of the movement-vaguely, however, and with no clearness, but as untrained men behave in fights; for they go round their opponents and often strike fine blows, but they do not fight on scientific principles, and so too these thinkers do not seem to know what they say; for it is evident that, as a rule, they make no use of their causes except to a small extent. For Anaxagoras uses reason as a deus ex machina for the making of the world, and when he is at a loss to tell from what cause something necessarily is, then he drags reason in, but in all other cases ascribes events to anything rather than to reason. And Empedocles, though he uses the causes to a greater extent than this, neither does so sufficiently nor attains consistency in their use. At least, in many cases he makes love segregate things, and strife aggregate them. For whenever the universe is dissolved into its elements by strife, fire is aggregated into one, and so is each of the other elements; but whenever again under the influence of love they come together into one, the parts must again be segregated out of each element.

Empedocles, then, in contrast with his precessors, was the first to introduce the dividing of this cause, not positing one source of movement, but different and contrary sources. Again, he was the first to speak of four material elements; yet he does not use four, but treats them as two only; he treats fire by itself, and its opposite-earth, air, and water-as one kind of thing. We may learn this by study of his verses.

This philosopher then, as we say, has spoken of the principles in this way, and made them of this number. Leucippus and his associate Democritus say that the full and the empty are the elements, calling the one being and the other non-being-the full and solid being being, the empty non-being (whence they say being no more is than non-being, because the solid no more is than the empty); and they make these the material causes of things. And as those who make the underlying substance one generate all other things by its modifications, supposing the rare and the dense to be the sources of the modifications, in the same way these philosophers say the differences in the elements are the causes of all other qualities. These differences, they say, are three-shape and order and position. For they say the real is differentiated only by 'rhythm and 'inter-contact' and 'turning'; and of these rhythm is shape, inter-contact is order, and turning is position; for A differs from N in shape, AN from NA in order, M from W in position. The question of movement-whence or how it is to belong to things-these thinkers, like the others, lazily neglected.

Regarding the two causes, then, as we say, the inquiry seems to have been pushed thus far by the early philosophers.
`;

export default text;
