const text = `
Our review of those who have spoken about first principles and reality and of the way in which they have spoken, has been concise and summary; but yet we have learnt this much from them, that of those who speak about 'principle' and 'cause' no one has mentioned any principle except those which have been distinguished in our work on nature, but all evidently have some inkling of them, though only vaguely. For some speak of the first principle as matter, whether they suppose one or more first principles, and whether they suppose this to be a body or to be incorporeal; e.g. Plato spoke of the great and the small, the Italians of the infinite, Empedocles of fire, earth, water, and air, Anaxagoras of the infinity of things composed of similar parts. These, then, have all had a notion of this kind of cause, and so have all who speak of air or fire or water, or something denser than fire and rarer than air; for some have said the prime element is of this kind.

These thinkers grasped this cause only; but certain others have mentioned the source of movement, e.g. those who make friendship and strife, or reason, or love, a principle.

The essence, i.e. the substantial reality, no one has expressed distinctly. It is hinted at chiefly by those who believe in the Forms; for they do not suppose either that the Forms are the matter of sensible things, and the One the matter of the Forms, or that they are the source of movement (for they say these are causes rather of immobility and of being at rest), but they furnish the Forms as the essence of every other thing, and the One as the essence of the Forms.

That for whose sake actions and changes and movements take place, they assert to be a cause in a way, but not in this way, i.e. not in the way in which it is its nature to be a cause. For those who speak of reason or friendship class these causes as goods; they do not speak, however, as if anything that exists either existed or came into being for the sake of these, but as if movements started from these. In the same way those who say the One or the existent is the good, say that it is the cause of substance, but not that substance either is or comes to be for the sake of this. Therefore it turns out that in a sense they both say and do not say the good is a cause; for they do not call it a cause qua good but only incidentally.

All these thinkers then, as they cannot pitch on another cause, seem to testify that we have determined rightly both how many and of what sort the causes are. Besides this it is plain that when the causes are being looked for, either all four must be sought thus or they must be sought in one of these four ways. Let us next discuss the possible difficulties with regard to the way in which each of these thinkers has spoken, and with regard to his situation relatively to the first principles.
`;

export default text;
