const text = `
After the systems we have named came the philosophy of Plato, which in most respects followed these thinkers, but had pecullarities that distinguished it from the philosophy of the Italians. For, having in his youth first become familiar with Cratylus and with the Heraclitean doctrines (that all sensible things are ever in a state of flux and there is no knowledge about them), these views he held even in later years. Socrates, however, was busying himself about ethical matters and neglecting the world of nature as a whole but seeking the universal in these ethical matters, and fixed thought for the first time on definitions; Plato accepted his teaching, but held that the problem applied not to sensible things but to entities of another kind-for this reason, that the common definition could not be a definition of any sensible thing, as they were always changing. Things of this other sort, then, he called Ideas, and sensible things, he said, were all named after these, and in virtue of a relation to these; for the many existed by participation in the Ideas that have the same name as they. Only the name 'participation' was new; for the Pythagoreans say that things exist by 'imitation' of numbers, and Plato says they exist by participation, changing the name. But what the participation or the imitation of the Forms could be they left an open question.

Further, besides sensible things and Forms he says there are the objects of mathematics, which occupy an intermediate position, differing from sensible things in being eternal and unchangeable, from Forms in that there are many alike, while the Form itself is in each case unique.

Since the Forms were the causes of all other things, he thought their elements were the elements of all things. As matter, the great and the small were principles; as essential reality, the One; for from the great and the small, by participation in the One, come the Numbers.

But he agreed with the Pythagoreans in saying that the One is substance and not a predicate of something else; and in saying that the Numbers are the causes of the reality of other things he agreed with them; but positing a dyad and constructing the infinite out of great and small, instead of treating the infinite as one, is peculiar to him; and so is his view that the Numbers exist apart from sensible things, while they say that the things themselves are Numbers, and do not place the objects of mathematics between Forms and sensible things. His divergence from the Pythagoreans in making the One and the Numbers separate from things, and his introduction of the Forms, were due to his inquiries in the region of definitions (for the earlier thinkers had no tincture of dialectic), and his making the other entity besides the One a dyad was due to the belief that the numbers, except those which were prime, could be neatly produced out of the dyad as out of some plastic material. Yet what happens is the contrary; the theory is not a reasonable one. For they make many things out of the matter, and the form generates only once, but what we observe is that one table is made from one matter, while the man who applies the form, though he is one, makes many tables. And the relation of the male to the female is similar; for the latter is impregnated by one copulation, but the male impregnates many females; yet these are analogues of those first principles.

Plato, then, declared himself thus on the points in question; it is evident from what has been said that he has used only two causes, that of the essence and the material cause (for the Forms are the causes of the essence of all other things, and the One is the cause of the essence of the Forms); and it is evident what the underlying matter is, of which the Forms are predicated in the case of sensible things, and the One in the case of Forms, viz. that this is a dyad, the great and the small. Further, he has assigned the cause of good and that of evil to the elements, one to each of the two, as we say some of his predecessors sought to do, e.g. Empedocles and Anaxagoras.
`;

export default text;
