const text = `
Those, then, who say the universe is one and posit one kind of thing as matter, and as corporeal matter which has spatial magnitude, evidently go astray in many ways. For they posit the elements of bodies only, not of incorporeal things, though there are also incorporeal things. And in trying to state the causes of generation and destruction, and in giving a physical account of all things, they do away with the cause of movement. Further, they err in not positing the substance, i.e. the essence, as the cause of anything, and besides this in lightly calling any of the simple bodies except earth the first principle, without inquiring how they are produced out of one anothers-I mean fire, water, earth, and air. For some things are produced out of each other by combination, others by separation, and this makes the greatest difference to their priority and posteriority. For (1) in a way the property of being most elementary of all would seem to belong to the first thing from which they are produced by combination, and this property would belong to the most fine-grained and subtle of bodies. For this reason those who make fire the principle would be most in agreement with this argument. But each of the other thinkers agrees that the element of corporeal things is of this sort. At least none of those who named one element claimed that earth was the element, evidently because of the coarseness of its grain. (Of the other three elements each has found some judge on its side; for some maintain that fire, others that water, others that air is the element. Yet why, after all, do they not name earth also, as most men do? For people say all things are earth Hesiod says earth was produced first of corporeal things; so primitive and popular has the opinion been.) According to this argument, then, no one would be right who either says the first principle is any of the elements other than fire, or supposes it to be denser than air but rarer than water. But (2) if that which is later in generation is prior in nature, and that which is concocted and compounded is later in generation, the contrary of what we have been saying must be true,-water must be prior to air, and earth to water.

So much, then, for those who posit one cause such as we mentioned; but the same is true if one supposes more of these, as Empedocles says matter of things is four bodies. For he too is confronted by consequences some of which are the same as have been mentioned, while others are peculiar to him. For we see these bodies produced from one another, which implies that the same body does not always remain fire or earth (we have spoken about this in our works on nature); and regarding the cause of movement and the question whether we must posit one or two, he must be thought to have spoken neither correctly nor altogether plausibly. And in general, change of quality is necessarily done away with for those who speak thus, for on their view cold will not come from hot nor hot from cold. For if it did there would be something that accepted the contraries themselves, and there would be some one entity that became fire and water, which Empedocles denies.

As regards Anaxagoras, if one were to suppose that he said there were two elements, the supposition would accord thoroughly with an argument which Anaxagoras himself did not state articulately, but which he must have accepted if any one had led him on to it. True, to say that in the beginning all things were mixed is absurd both on other grounds and because it follows that they must have existed before in an unmixed form, and because nature does not allow any chance thing to be mixed with any chance thing, and also because on this view modifications and accidents could be separated from substances (for the same things which are mixed can be separated); yet if one were to follow him up, piecing together what he means, he would perhaps be seen to be somewhat modern in his views. For when nothing was separated out, evidently nothing could be truly asserted of the substance that then existed. I mean, e.g. that it was neither white nor black, nor grey nor any other colour, but of necessity colourless; for if it had been coloured, it would have had one of these colours. And similarly, by this same argument, it was flavourless, nor had it any similar attribute; for it could not be either of any quality or of any size, nor could it be any definite kind of thing. For if it were, one of the particular forms would have belonged to it, and this is impossible, since all were mixed together; for the particular form would necessarily have been already separated out, but he all were mixed except reason, and this alone was unmixed and pure. From this it follows, then, that he must say the principles are the One (for this is simple and unmixed) and the Other, which is of such a nature as we suppose the indefinite to be before it is defined and partakes of some form. Therefore, while expressing himself neither rightly nor clearly, he means something like what the later thinkers say and what is now more clearly seen to be the case.

But these thinkers are, after all, at home only in arguments about generation and destruction and movement; for it is practically only of this sort of substance that they seek the principles and the causes. But those who extend their vision to all things that exist, and of existing things suppose some to be perceptible and others not perceptible, evidently study both classes, which is all the more reason why one should devote some time to seeing what is good in their views and what bad from the standpoint of the inquiry we have now before us.

The 'Pythagoreans' treat of principles and elements stranger than those of the physical philosophers (the reason is that they got the principles from non-sensible things, for the objects of mathematics, except those of astronomy, are of the class of things without movement); yet their discussions and investigations are all about nature; for they generate the heavens, and with regard to their parts and attributes and functions they observe the phenomena, and use up the principles and the causes in explaining these, which implies that they agree with the others, the physical philosophers, that the real is just all that which is perceptible and contained by the so-called 'heavens'. But the causes and the principles which they mention are, as we said, sufficient to act as steps even up to the higher realms of reality, and are more suited to these than to theories about nature. They do not tell us at all, however, how there can be movement if limit and unlimited and odd and even are the only things assumed, or how without movement and change there can be generation and destruction, or the bodies that move through the heavens can do what they do.

Further, if one either granted them that spatial magnitude consists of these elements, or this were proved, still how would some bodies be light and others have weight? To judge from what they assume and maintain they are speaking no more of mathematical bodies than of perceptible; hence they have said nothing whatever about fire or earth or the other bodies of this sort, I suppose because they have nothing to say which applies peculiarly to perceptible things.

Further, how are we to combine the beliefs that the attributes of number, and number itself, are causes of what exists and happens in the heavens both from the beginning and now, and that there is no other number than this number out of which the world is composed? When in one particular region they place opinion and opportunity, and, a little above or below, injustice and decision or mixture, and allege, as proof, that each of these is a number, and that there happens to be already in this place a plurality of the extended bodies composed of numbers, because these attributes of number attach to the various places,-this being so, is this number, which we must suppose each of these abstractions to be, the same number which is exhibited in the material universe, or is it another than this? Plato says it is different; yet even he thinks that both these bodies and their causes are numbers, but that the intelligible numbers are causes, while the others are sensible.
`;

export default text;
