const text = `
Contemporaneously with these philosophers and before them, the so-called Pythagoreans, who were the first to take up mathematics, not only advanced this study, but also having been brought up in it they thought its principles were the principles of all things. Since of these principles numbers are by nature the first, and in numbers they seemed to see many resemblances to the things that exist and come into being-more than in fire and earth and water (such and such a modification of numbers being justice, another being soul and reason, another being opportunity-and similarly almost all other things being numerically expressible); since, again, they saw that the modifications and the ratios of the musical scales were expressible in numbers;-since, then, all other things seemed in their whole nature to be modelled on numbers, and numbers seemed to be the first things in the whole of nature, they supposed the elements of numbers to be the elements of all things, and the whole heaven to be a musical scale and a number. And all the properties of numbers and scales which they could show to agree with the attributes and parts and the whole arrangement of the heavens, they collected and fitted into their scheme; and if there was a gap anywhere, they readily made additions so as to make their whole theory coherent. E.g. as the number 10 is thought to be perfect and to comprise the whole nature of numbers, they say that the bodies which move through the heavens are ten, but as the visible bodies are only nine, to meet this they invent a tenth--the 'counter-earth'. We have discussed these matters more exactly elsewhere.

But the object of our review is that we may learn from these philosophers also what they suppose to be the principles and how these fall under the causes we have named. Evidently, then, these thinkers also consider that number is the principle both as matter for things and as forming both their modifications and their permanent states, and hold that the elements of number are the even and the odd, and that of these the latter is limited, and the former unlimited; and that the One proceeds from both of these (for it is both even and odd), and number from the One; and that the whole heaven, as has been said, is numbers.

Other members of this same school say there are ten principles, which they arrange in two columns of cognates-limit and unlimited, odd and even, one and plurality, right and left, male and female, resting and moving, straight and curved, light and darkness, good and bad, square and oblong. In this way Alcmaeon of Croton seems also to have conceived the matter, and either he got this view from them or they got it from him; for he expressed himself similarly to them. For he says most human affairs go in pairs, meaning not definite contrarieties such as the Pythagoreans speak of, but any chance contrarieties, e.g. white and black, sweet and bitter, good and bad, great and small. He threw out indefinite suggestions about the other contrarieties, but the Pythagoreans declared both how many and which their contraricties are.

From both these schools, then, we can learn this much, that the contraries are the principles of things; and how many these principles are and which they are, we can learn from one of the two schools. But how these principles can be brought together under the causes we have named has not been clearly and articulately stated by them; they seem, however, to range the elements under the head of matter; for out of these as immanent parts they say substance is composed and moulded.

From these facts we may sufficiently perceive the meaning of the ancients who said the elements of nature were more than one; but there are some who spoke of the universe as if it were one entity, though they were not all alike either in the excellence of their statement or in its conformity to the facts of nature. The discussion of them is in no way appropriate to our present investigation of causes, for. they do not, like some of the natural philosophers, assume being to be one and yet generate it out of the one as out of matter, but they speak in another way; those others add change, since they generate the universe, but these thinkers say the universe is unchangeable. Yet this much is germane to the present inquiry: Parmenides seems to fasten on that which is one in definition, Melissus on that which is one in matter, for which reason the former says that it is limited, the latter that it is unlimited; while Xenophanes, the first of these partisans of the One (for Parmenides is said to have been his pupil), gave no clear statement, nor does he seem to have grasped the nature of either of these causes, but with reference to the whole material universe he says the One is God. Now these thinkers, as we said, must be neglected for the purposes of the present inquiry-two of them entirely, as being a little too naive, viz. Xenophanes and Melissus; but Parmenides seems in places to speak with more insight. For, claiming that, besides the existent, nothing non-existent exists, he thinks that of necessity one thing exists, viz. the existent and nothing else (on this we have spoken more clearly in our work on nature), but being forced to follow the observed facts, and supposing the existence of that which is one in definition, but more than one according to our sensations, he now posits two causes and two principles, calling them hot and cold, i.e. fire and earth; and of these he ranges the hot with the existent, and the other with the non-existent.

From what has been said, then, and from the wise men who have now sat in council with us, we have got thus much-on the one hand from the earliest philosophers, who regard the first principle as corporeal (for water and fire and such things are bodies), and of whom some suppose that there is one corporeal principle, others that there are more than one, but both put these under the head of matter; and on the other hand from some who posit both this cause and besides this the source of movement, which we have got from some as single and from others as twofold.

Down to the Italian school, then, and apart from it, philosophers have treated these subjects rather obscurely, except that, as we said, they have in fact used two kinds of cause, and one of these-the source of movement-some treat as one and others as two. But the Pythagoreans have said in the same way that there are two principles, but added this much, which is peculiar to them, that they thought that finitude and infinity were not attributes of certain other things, e.g. of fire or earth or anything else of this kind, but that infinity itself and unity itself were the substance of the things of which they are predicated. This is why number was the substance of all things. On this subject, then, they expressed themselves thus; and regarding the question of essence they began to make statements and definitions, but treated the matter too simply. For they both defined superficially and thought that the first subject of which a given definition was predicable was the substance of the thing defined, as if one supposed that 'double' and '2' were the same, because 2 is the first thing of which 'double' is predicable. But surely to be double and to be 2 are not the same; if they are, one thing will be many-a consequence which they actually drew. From the earlier philosophers, then, and from their successors we can learn thus much.
`;

export default text;
