const text = `
Let us leave the Pythagoreans for the present; for it is enough to have touched on them as much as we have done. But as for those who posit the Ideas as causes, firstly, in seeking to grasp the causes of the things around us, they introduced others equal in number to these, as if a man who wanted to count things thought he would not be able to do it while they were few, but tried to count them when he had added to their number. For the Forms are practically equal to-or not fewer than-the things, in trying to explain which these thinkers proceeded from them to the Forms. For to each thing there answers an entity which has the same name and exists apart from the substances, and so also in the case of all other groups there is a one over many, whether the many are in this world or are eternal.

Further, of the ways in which we prove that the Forms exist, none is convincing; for from some no inference necessarily follows, and from some arise Forms even of things of which we think there are no Forms. For according to the arguments from the existence of the sciences there will be Forms of all things of which there are sciences and according to the 'one over many' argument there will be Forms even of negations, and according to the argument that there is an object for thought even when the thing has perished, there will be Forms of perishable things; for we have an image of these. Further, of the more accurate arguments, some lead to Ideas of relations, of which we say there is no independent class, and others introduce the 'third man'.

And in general the arguments for the Forms destroy the things for whose existence we are more zealous than for the existence of the Ideas; for it follows that not the dyad but number is first, i.e. that the relative is prior to the absolute,-besides all the other points on which certain people by following out the opinions held about the Ideas have come into conflict with the principles of the theory.

Further, according to the assumption on which our belief in the Ideas rests, there will be Forms not only of substances but also of many other things (for the concept is single not only in the case of substances but also in the other cases, and there are sciences not only of substance but also of other things, and a thousand other such difficulties confront them). But according to the necessities of the case and the opinions held about the Forms, if Forms can be shared in there must be Ideas of substances only. For they are not shared in incidentally, but a thing must share in its Form as in something not predicated of a subject (by 'being shared in incidentally' I mean that e.g. if a thing shares in 'double itself', it shares also in 'eternal', but incidentally; for 'eternal' happens to be predicable of the 'double'). Therefore the Forms will be substance; but the same terms indicate substance in this and in the ideal world (or what will be the meaning of saying that there is something apart from the particulars-the one over many?). And if the Ideas and the particulars that share in them have the same form, there will be something common to these; for why should '2' be one and the same in the perishable 2's or in those which are many but eternal, and not the same in the '2' itself' as in the particular 2? But if they have not the same form, they must have only the name in common, and it is as if one were to call both Callias and a wooden image a 'man', without observing any community between them.

Above all one might discuss the question what on earth the Forms contribute to sensible things, either to those that are eternal or to those that come into being and cease to be. For they cause neither movement nor any change in them. But again they help in no wise either towards the knowledge of the other things (for they are not even the substance of these, else they would have been in them), or towards their being, if they are not in the particulars which share in them; though if they were, they might be thought to be causes, as white causes whiteness in a white object by entering into its composition. But this argument, which first Anaxagoras and later Eudoxus and certain others used, is very easily upset; for it is not difficult to collect many insuperable objections to such a view.

But, further, all other things cannot come from the Forms in any of the usual senses of 'from'. And to say that they are patterns and the other things share in them is to use empty words and poetical metaphors. For what is it that works, looking to the Ideas? And anything can either be, or become, like another without being copied from it, so that whether Socrates or not a man Socrates like might come to be; and evidently this might be so even if Socrates were eternal. And there will be several patterns of the same thing, and therefore several Forms; e.g. 'animal' and 'two-footed' and also 'man himself' will be Forms of man. Again, the Forms are patterns not only sensible things, but of Forms themselves also; i.e. the genus, as genus of various species, will be so; therefore the same thing will be pattern and copy.

Again, it would seem impossible that the substance and that of which it is the substance should exist apart; how, therefore, could the Ideas, being the substances of things, exist apart? In the Phaedo' the case is stated in this way-that the Forms are causes both of being and of becoming; yet when the Forms exist, still the things that share in them do not come into being, unless there is something to originate movement; and many other things come into being (e.g. a house or a ring) of which we say there are no Forms. Clearly, therefore, even the other things can both be and come into being owing to such causes as produce the things just mentioned.

Again, if the Forms are numbers, how can they be causes? Is it because existing things are other numbers, e.g. one number is man, another is Socrates, another Callias? Why then are the one set of numbers causes of the other set? It will not make any difference even if the former are eternal and the latter are not. But if it is because things in this sensible world (e.g. harmony) are ratios of numbers, evidently the things between which they are ratios are some one class of things. If, then, this--the matter--is some definite thing, evidently the numbers themselves too will be ratios of something to something else. E.g. if Callias is a numerical ratio between fire and earth and water and air, his Idea also will be a number of certain other underlying things; and man himself, whether it is a number in a sense or not, will still be a numerical ratio of certain things and not a number proper, nor will it be a of number merely because it is a numerical ratio.

Again, from many numbers one number is produced, but how can one Form come from many Forms? And if the number comes not from the many numbers themselves but from the units in them, e.g. in 10,000, how is it with the units? If they are specifically alike, numerous absurdities will follow, and also if they are not alike (neither the units in one number being themselves like one another nor those in other numbers being all like to all); for in what will they differ, as they are without quality? This is not a plausible view, nor is it consistent with our thought on the matter.

Further, they must set up a second kind of number (with which arithmetic deals), and all the objects which are called 'intermediate' by some thinkers; and how do these exist or from what principles do they proceed? Or why must they be intermediate between the things in this sensible world and the things-themselves?

Further, the units in must each come from a prior but this is impossible.

Further, why is a number, when taken all together, one?

Again, besides what has been said, if the units are diverse the Platonists should have spoken like those who say there are four, or two, elements; for each of these thinkers gives the name of element not to that which is common, e.g. to body, but to fire and earth, whether there is something common to them, viz. body, or not. But in fact the Platonists speak as if the One were homogeneous like fire or water; and if this is so, the numbers will not be substances. Evidently, if there is a One itself and this is a first principle, 'one' is being used in more than one sense; for otherwise the theory is impossible.

When we wish to reduce substances to their principles, we state that lines come from the short and long (i.e. from a kind of small and great), and the plane from the broad and narrow, and body from the deep and shallow. Yet how then can either the plane contain a line, or the solid a line or a plane? For the broad and narrow is a different class from the deep and shallow. Therefore, just as number is not present in these, because the many and few are different from these, evidently no other of the higher classes will be present in the lower. But again the broad is not a genus which includes the deep, for then the solid would have been a species of plane. Further, from what principle will the presence of the points in the line be derived? Plato even used to object to this class of things as being a geometrical fiction. He gave the name of principle of the line-and this he often posited-to the indivisible lines. Yet these must have a limit; therefore the argument from which the existence of the line follows proves also the existence of the point.

In general, though philosophy seeks the cause of perceptible things, we have given this up (for we say nothing of the cause from which change takes its start), but while we fancy we are stating the substance of perceptible things, we assert the existence of a second class of substances, while our account of the way in which they are the substances of perceptible things is empty talk; for 'sharing', as we said before, means nothing.

Nor have the Forms any connexion with what we see to be the cause in the case of the arts, that for whose sake both all mind and the whole of nature are operative,-with this cause which we assert to be one of the first principles; but mathematics has come to be identical with philosophy for modern thinkers, though they say that it should be studied for the sake of other things. Further, one might suppose that the substance which according to them underlies as matter is too mathematical, and is a predicate and differentia of the substance, ie. of the matter, rather than matter itself; i.e. the great and the small are like the rare and the dense which the physical philosophers speak of, calling these the primary differentiae of the substratum; for these are a kind of excess and defect. And regarding movement, if the great and the small are to he movement, evidently the Forms will be moved; but if they are not to be movement, whence did movement come? The whole study of nature has been annihilated.

And what is thought to be easy-to show that all things are one-is not done; for what is proved by the method of setting out instances is not that all things are one but that there is a One itself,-if we grant all the assumptions. And not even this follows, if we do not grant that the universal is a genus; and this in some cases it cannot be.

Nor can it be explained either how the lines and planes and solids that come after the numbers exist or can exist, or what significance they have; for these can neither be Forms (for they are not numbers), nor the intermediates (for those are the objects of mathematics), nor the perishable things. This is evidently a distinct fourth class.

In general, if we search for the elements of existing things without distinguishing the many senses in which things are said to exist, we cannot find them, especially if the search for the elements of which things are made is conducted in this manner. For it is surely impossible to discover what 'acting' or 'being acted on', or 'the straight', is made of, but if elements can be discovered at all, it is only the elements of substances; therefore either to seek the elements of all existing things or to think one has them is incorrect.

And how could we learn the elements of all things? Evidently we cannot start by knowing anything before. For as he who is learning geometry, though he may know other things before, knows none of the things with which the science deals and about which he is to learn, so is it in all other cases. Therefore if there is a science of all things, such as some assert to exist, he who is learning this will know nothing before. Yet all learning is by means of premisses which are (either all or some of them) known before,-whether the learning be by demonstration or by definitions; for the elements of the definition must be known before and be familiar; and learning by induction proceeds similarly. But again, if the science were actually innate, it were strange that we are unaware of our possession of the greatest of sciences.

Again, how is one to come to know what all things are made of, and how is this to be made evident? This also affords a difficulty; for there might be a conflict of opinion, as there is about certain syllables; some say za is made out of s and d and a, while others say it is a distinct sound and none of those that are familiar.

Further, how could we know the objects of sense without having the sense in question? Yet we ought to, if the elements of which all things consist, as complex sounds consist of the clements proper to sound, are the same.
`;

export default text;
